/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   iron-label.html
 */

/// <reference path="../polymer/types/polymer.d.ts" />

declare namespace Polymer {

  class IronLabel extends Polymer.Element {

    /**
     * An ID reference to another element that needs to be
     * labelled by this `iron-label` element.
     */
    for: string|null|undefined;
    _forElement: Element|null;
    attached(): void;
    ready(): void;

    /**
     * generate a unique id for this element
     */
    _generateLabelId(): void;
    _findTarget(): any;
    _tapHandler(ev: any): void;
    _applyLabelledBy(): void;
    _forChanged(): void;
  }
}

interface HTMLElementTagNameMap {
  "iron-label": Polymer.IronLabel;
}
