/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   zip-validator.html
 */

/// <reference path="../polymer/types/polymer.d.ts" />
/// <reference path="../iron-validator-behavior/iron-validator-behavior.d.ts" />

interface ZipValidatorElement extends Polymer.Element, Polymer.IronValidatorBehavior {
  validate(value: any): any;
}

interface HTMLElementTagNameMap {
  "zip-validator": ZipValidatorElement;
}
