/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   platinum-sw-elements.html
 */

/// <reference path="platinum-sw-cache.d.ts" />
/// <reference path="platinum-sw-fetch.d.ts" />
/// <reference path="platinum-sw-import-script.d.ts" />
/// <reference path="platinum-sw-offline-analytics.d.ts" />
/// <reference path="platinum-sw-register.d.ts" />

